feat: add plot generation for snp database

diff --git a/040_snp_sql/Snakefile b/040_snp_sql/Snakefile
--- a/040_snp_sql/Snakefile
+++ b/040_snp_sql/Snakefile
@@ -1,11 +1,13 @@
 rule all:
   input:
-    "150.db/snps.sqlite"
+    "150.db/snps.sqlite",
+    "160.figures/fig1_impact_severity.svg",
+    "160.figures/fig2_gene_impacts.svg"
 
 rule load_vcf_to_sqlite:
   input: 
     vcf="/lustre1/project/stg_00079/teaching/data/snps.annotated.vcf",
-    py_script="vcf_to_sqlite.py"
+    script="vcf_to_sqlite.py"
   output:
     db="150.db/snps.sqlite"
   log:
@@ -16,7 +18,23 @@ rule load_vcf_to_sqlite:
     
     export PATH=/lustre1/project/stg_00079/teaching/I0U19a_conda_2026/bin/:$PATH
 
-    python {input.py_script} --vcf {input.vcf} --db {output.db} > {log} 2>&1
+    python {input.script} --vcf {input.vcf} --db {output.db} > {log} 2>&1
     
 
+    """
+
+rule generate_figure:
+  input:
+    db="150.db/snps.sqlite",
+    script="generate_plots.py"
+  output:
+    fig1="160.figures/fig1_impact_severity.svg",
+    fig2="160.figures/fig2_gene_impacts.svg"
+  shell:
+    """
+    export PATH=/lustre1/project/stg_00079/teaching/I0U19a_conda_2026/bin/:$PATH
+
+    python {input.script} --db {input.db} --outdir 160.figures
+
+    [ -s {output.fig1} ] && [ -s {output.fig2} ] || {{ echo "Error: Figure generation failed or files are empty!"; exit 1; }}  
     """
